- search: " to to "
  replacement: " to "
  description: Avoid double "to"
- search: " the the "
  replacement: " the "
  description: Avoid double "the"
- search: " and and "
  replacement: " and "
  description: Avoid double "and"
